name: Release (dev)

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
      - 'doc/**'
      - 'examples/**'
    branches:
      - 'main'

jobs:
  run_tests:
    name: Run tests
    uses: l7mp/stunner/.github/workflows/test.yml@main

  push_stunner_to_registry:
    name: Push STUNner image to DockerHub
    needs: run_tests
    if: github.repository == 'l7mp/stunner'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: l7mp/stunnerd
          tags: |
            type=raw,value=dev

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  push_chart:
    name: Push helm charts to the repo
    if: github.repository == 'l7mp/stunner'
    needs: push_stunner_to_registry
    uses: l7mp/stunner/.github/workflows/publish--push-charts.yml@main
    with:
      dev: true
    secrets: inherit

  push_icetester_to_registry:
    name: Push icetester image to DockerHub
    needs: run_tests
    if: github.repository == 'l7mp/stunner'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: l7mp/icetester
          tags: |
            type=raw,value=dev

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.icetester
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
